export const SIGNIN_PENDING = "SIGNIN_PENDING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const LOGOUT = "LOGOUT";

export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const CLEAR_USER_IMAGE_URL = "CLEAR_USER_IMAGE_URL";
export const SET_USER_IMAGE_URL = "SET_USER_IMAGE_URL";

export const UPDATE_IMAGE_URL_PENDING = "UPDATE_IMAGE_URL_PENDING";
export const UPDATE_IMAGE_URL_SUCCESS = "UPDATE_IMAGE_URL_SUCCESS";
export const UPDATE_IMAGE_URL_ERROR = "UPDATE_IMAGE_URL_ERROR";

export const UPDATE_TEACHER_PROFILE_PENDING = "UPDATE_TEACHER_PROFILE_PENDING";
export const UPDATE_TEACHER_PROFILE_SUCCESS = "UPDATE_TEACHER_PROFILE_SUCCESS";
export const UPDATE_TEACHER_PROFILE_ERROR = "UPDATE_TEACHER_PROFILE_ERROR";

export const GET_SUBJECTS_PENDING = "GET_SUBJECTS_PENDING";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_ERROR = "GET_SUBJECTS_ERROR";

export const GET_LEVEL_PENDING = "GET_LEVEL_PENDING";
export const GET_LEVEL_SUCCESS = "GET_LEVEL_SUCCESS";
export const GET_LEVEL_ERROR = "GET_LEVEL_ERROR";
export const CHANGE_LEVEL_STATUS = "CHANGE_LEVEL_STATUS";
