export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_REFRESH = 'REGISTER_REFRESH';

export const FACEBOOK_LOGIN_START = 'FACEBOOK_LOGIN_START';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REFRESH = 'LOGIN_REFRESH';

export const SELECTED_TAB = 'SELECTED_TAB';

export const SIGNIN_PENDING = 'SIGNIN_PENDING';
export const SIGNIN_APROVED = 'SIGNIN_APROVED';
export const SIGNIN_REJECT = 'SIGNIN_REJECT';

export const CREATE_SKILL = 'CREATE_SKILL';
export const CREATE_SKILL_START = 'CREATE_SKILL_START';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const CREATE_SKILL_FAIL = 'CREATE_SKILL_FAIL';

export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_SKILL_START = 'UPDATE_SKILL_START';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_FAIL = 'UPDATE_SKILL_FAIL';

export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_SKILL_START = 'DELETE_SKILL_START';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAIL = 'DELETE_SKILL_FAIL';

export const GET_LIST_SKILL = 'GET_LIST_SKILL';
export const GET_LIST_SKILL_START = 'GET_LIST_SKILL_START';
export const GET_LIST_SKILL_SUCCESS = 'GET_LIST_SKILL_SUCCESS';
export const GET_LIST_SKILL_FAIL = 'GET_LIST_SKILL_FAIL';

export const REFRESH_MESSAGE_CRUD = 'REFRESH_MESSAGE_CRUD';

export const GET_LIST_USER = 'GET_LIST_USER';
export const GET_LIST_USER_START = 'GET_LIST_USER_START';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_FAIL = 'GET_LIST_USER_FAIL';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const CREATE_LOCATION = 'CREATE_LOCATION';
export const CREATE_LOCATION_START = 'CREATE_LOCATION_START';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_FAIL = 'CREATE_LOCATION_FAIL';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_START = 'UPDATE_LOCATION_START';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAIL = 'UPDATE_LOCATION_FAIL';

export const GET_LIST_LOCATION = 'GET_LIST_LOCATION';
export const GET_LIST_LOCATION_START = 'GET_LIST_LOCATION_START';
export const GET_LIST_LOCATION_SUCCESS = 'GET_LIST_LOCATION_SUCCESS';
export const GET_LIST_LOCATION_FAIL = 'GET_LIST_LOCATION_FAIL';

export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_LOCATION_START = 'DELETE_LOCATION_START';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAIL = 'DELETE_LOCATION_FAIL';

export const CREATE_LEVEL = 'CREATE_LEVEL';
export const CREATE_LEVEL_START = 'CREATE_LEVEL_START';
export const CREATE_LEVEL_SUCCESS = 'CREATE_LEVEL_SUCCESS';
export const CREATE_LEVEL_FAIL = 'CREATE_LEVEL_FAIL';

export const UPDATE_LEVEL = 'UPDATE_LEVEL';
export const UPDATE_LEVEL_START = 'UPDATE_LEVEL_START';
export const UPDATE_LEVEL_SUCCESS = 'UPDATE_LEVEL_SUCCESS';
export const UPDATE_LEVEL_FAIL = 'UPDATE_LEVEL_FAIL';

export const GET_LIST_LEVEL = 'GET_LIST_LEVEL';
export const GET_LIST_LEVEL_START = 'GET_LIST_LEVEL_START';
export const GET_LIST_LEVEL_SUCCESS = 'GET_LIST_LEVEL_SUCCESS';
export const GET_LIST_LEVEL_FAIL = 'GET_LIST_LEVEL_FAIL';

export const DELETE_LEVEL = 'DELETE_LEVEL';
export const DELETE_LEVEL_START = 'DELETE_LEVEL_START';
export const DELETE_LEVEL_SUCCESS = 'DELETE_LEVEL_SUCCESS';
export const DELETE_LEVEL_FAIL = 'DELETE_LEVEL_FAIL';

export const CREATE_LEVEL_EDUCATION = 'CREATE_LEVEL_EDUCATION';
export const CREATE_LEVEL_EDUCATION_START = 'CREATE_LEVEL_EDUCATION_START';
export const CREATE_LEVEL_EDUCATION_SUCCESS = 'CREATE_LEVEL_EDUCATION_SUCCESS';
export const CREATE_LEVEL_EDUCATION_FAIL = 'CREATE_LEVEL_EDUCATION_FAIL';

export const UPDATE_LEVEL_EDUCATION = 'UPDATE_LEVEL_EDUCATION';
export const UPDATE_LEVEL_EDUCATION_START = 'UPDATE_LEVEL_EDUCATION_START';
export const UPDATE_LEVEL_EDUCATION_SUCCESS = 'UPDATE_LEVEL_EDUCATION_SUCCESS';
export const UPDATE_LEVEL_EDUCATION_FAIL = 'UPDATE_LEVEL_EDUCATION_FAIL';

export const GET_LIST_LEVEL_EDUCATION = 'GET_LIST_LEVEL_EDUCATION';
export const GET_LIST_LEVEL_EDUCATION_START = 'GET_LIST_LEVEL_EDUCATION_START';
export const GET_LIST_LEVEL_EDUCATION_SUCCESS = 'GET_LIST_LEVEL_EDUCATION_SUCCESS';
export const GET_LIST_LEVEL_EDUCATION_FAIL = 'GET_LIST_LEVEL_EDUCATION_FAIL';

export const DELETE_LEVEL_EDUCATION = 'DELETE_LEVEL_EDUCATION';
export const DELETE_LEVEL_EDUCATION_START = 'DELETE_LEVEL_EDUCATION_START';
export const DELETE_LEVEL_EDUCATION_SUCCESS = 'DELETE_LEVEL_EDUCATION_SUCCESS';
export const DELETE_LEVEL_EDUCATION_FAIL = 'DELETE_LEVEL_EDUCATION_FAIL';

export const GET_LIST_CONTRACT = 'GET_LIST_CONTRACT';
export const GET_LIST_CONTRACT_START = 'GET_LIST_CONTRACT_START';
export const GET_LIST_CONTRACT_SUCCESS = 'GET_LIST_CONTRACT_SUCCESS';
export const GET_LIST_CONTRACT_FAIL = 'GET_LIST_CONTRACT_FAIL';

export const GET_DETAIL_USER = 'GET_DETAIL_USER';
export const GET_DETAIL_USER_START = 'GET_DETAIL_USER_START';
export const GET_DETAIL_USER_SUCCESS = 'GET_DETAIL_USER_SUCCESS';
export const GET_DETAIL_USER_FAIL = 'GET_DETAIL_USER_FAIL';

export const GET_LIST_COMPLAIN = 'GET_LIST_COMPLAIN';
export const GET_LIST_COMPLAIN_START = 'GET_LIST_COMPLAIN_START';
export const GET_LIST_COMPLAIN_SUCCESS = 'GET_LIST_COMPLAIN_SUCCESS';
export const GET_LIST_COMPLAIN_FAIL = 'GET_LIST_COMPLAIN_FAIL';

export const UPDATE_STATUS_COMPLAIN = 'UPDATE_STATUS_COMPLAIN';
export const UPDATE_STATUS_COMPLAIN_START = 'UPDATE_STATUS_COMPLAIN_START';
export const UPDATE_STATUS_COMPLAIN_SUCCESS = 'UPDATE_STATUS_COMPLAIN_SUCCESS';
export const UPDATE_STATUS_COMPLAIN_FAIL = 'UPDATE_STATUS_COMPLAIN_FAIL';

export const GET_CHAT_USER = 'GET_CHAT_USER';
export const GET_CHAT_USER_START = 'GET_CHAT_USER_START';
export const GET_CHAT_USER_SUCCESS = 'GET_CHAT_USER_SUCCESS';
export const GET_CHAT_USER_FAIL = 'GET_CHAT_USER_FAIL';

export const GET_TOP_USER = 'GET_TOP_USER';
export const GET_TOP_USER_START = 'GET_TOP_USER_START';
export const GET_TOP_USER_SUCCESS = 'GET_TOP_USER_SUCCESS';
export const GET_TOP_USER_FAIL = 'GET_TOP_USER_FAIL';